import 'package:flutter/material.dart';

final List<String> artists = [
  'BLACKPINK', 'Anuv Jain', 'Taylor Swift', 'LISA', 'Doja Cat', 'Kali Uchis'
];

final List imgs = [
  'assets/images/blackpink.jpg',
  'assets/images/anuv.jfif',
  'assets/images/ts.jfif',
  'assets/images/lisa.jpg',
  'assets/images/doja.jpg',
  'assets/images/kaliuchis.jfif'
];

final List<String> genres = [
  'Podcasts',
  'Live Events',
  'Made For You',
  'New Releases',
  'Hindi',
  'Punjabi',
  'Tamil',
  'Telugu',
  'Charts',
  'Pop',
  'Indie',
  'Trending',
  'Love',
  'Discover',
  'Radio',
  'Mood',
  'Party',
  'Devotional',
  'Decades',
  'Hip-Hop',
  'Dance/Electronic',
  'Student',
  'Chill',
  'Gaming',
  'K-Pop',
  'Workout',
  'RADAR',
  'EQUAL',
  'Fresh Finds',
  'Rock',
  'Sleep',
  'Indian Classical',
  'Instrumental',
  'Spotify Singles',
  'At Home',
  'Country',
  'R&B',
  'Metal',
  'Jazz',
  'Classical',
  'Folk and Acoustic',
  'Focus',
  'Disney',
  'Soul',
  'Children & Family',
  'Anime',
  'TV&Movies',
  'Punk',
  'Ambient',
  'Blues',
  'Cooking And Dining',
  'Alternative',
  'Wellness',
  'Travel',
  'Caribbean',
  'Afro',
  'Songwriters',
  'Nature & Noise',
  'Funk & Disco',
  'League of Legends',
  'Summer',
  'Netflix',
  'Asian Pacific Islander Heritage Month',
  'GLOW',
  'Music+Talk',
  'Latin',
  'Tastemakers'
];

final List<Color> bg = [
  Colors.orange, Colors.deepPurpleAccent, Colors.blueAccent, Colors.pinkAccent, Colors.red,
  Colors.purpleAccent, Colors.brown.shade300, Colors.deepOrangeAccent, Colors.purpleAccent,
  Colors.redAccent, Colors.purple.shade300, Colors.deepPurpleAccent, Colors.pinkAccent, Colors.lightBlue,
  Colors.brown.shade200, Colors.yellow.shade900, Colors.yellow.shade700, Colors.orange, Colors.yellow.shade700,
  Colors.orange, Colors.deepPurpleAccent, Colors.blueAccent, Colors.pinkAccent, Colors.red,
  Colors.purpleAccent, Colors.brown.shade300, Colors.deepOrangeAccent, Colors.purpleAccent,
  Colors.redAccent, Colors.purple.shade300, Colors.deepPurpleAccent, Colors.pinkAccent, Colors.lightBlue,
  Colors.brown.shade200, Colors.yellow.shade900, Colors.yellow.shade700, Colors.orange, Colors.yellow.shade700,
  Colors.orange, Colors.deepPurpleAccent, Colors.blueAccent, Colors.pinkAccent, Colors.red,
  Colors.purpleAccent, Colors.brown.shade300, Colors.deepOrangeAccent, Colors.purpleAccent,
  Colors.redAccent, Colors.purple.shade300, Colors.deepPurpleAccent, Colors.pinkAccent, Colors.lightBlue,
  Colors.brown.shade200, Colors.yellow.shade900, Colors.yellow.shade700, Colors.orange, Colors.yellow.shade700,
  Colors.deepPurpleAccent, Colors.blueAccent, Colors.pinkAccent, Colors.red,
  Colors.purpleAccent, Colors.brown.shade300, Colors.deepOrangeAccent, Colors.deepPurpleAccent, Colors.blueAccent, Colors.pinkAccent,
];
